name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_ci:
    name: Run CI
    runs-on: ubuntu-latest
    container:
        image: node:10.15
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn_cache_dir_path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1.0.0
        id: yarn_cache
        with:
          path: ${{ steps.yarn_cache_dir_path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependecies
        run: yarn

      - name: Run tests
        run: yarn test:CI